name: deta_drive
description: A dart helper library for Deta Drive cloud storage 
version: 1.0.0
homepage: https://www..com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  path:
  dio:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
